const translations = {
    'ro': {
        'nav_home': 'Acasă',
        'nav_about': 'Despre Noi',
        'nav_products': 'Produse și Servicii',
        'nav_projects': 'Proiecte',
        'nav_articles': 'Articole',
        'nav_contact': 'Contact',
        'nav_estimate': 'Estimare Cost',
        'hero_title': 'Sisteme Pluviale Premium',
        'hero_subtitle': 'Soluții inovatoare din tablă pentru casa și acoperișul tău. Fără îmbinări, fără griji.',
        'hero_cta': 'Vezi Proiectele',
        'services_title': 'Produsele și Serviciile Noastre',
        'service_1_title': 'Design Arhitectural',
        'service_1_desc': 'Arhitectura casei tale are nevoie de finisaje de calitate și funcționale.',
        'service_2_title': 'Calitate Garantată',
        'service_2_desc': 'Garanție Tehnică 30 ani + Garanție Estetică 20 ani.',
        'service_3_title': 'Echipă Profesionistă',
        'service_3_desc': 'Fabricare direct în locație și montaj profesionist.',
        'stats_projects': 'Proiecte Realizate',
        'stats_gutters': 'Metri de Jgheaburi',
        'stats_clients': 'Clienți Mulțumiți',
        'projects_title': 'Proiecte Recente',
        'testimonials_title': 'Ce Spun Clienții',
        'contact_title': 'Contactează-ne',
        'contact_name': 'Nume',
        'contact_email': 'Email',
        'contact_message': 'Mesaj',
        'contact_send': 'Trimite Mesaj',
        'contact_phone_label': 'Telefon',
        'contact_email_label': 'Email',
        'contact_schedule_label': 'Program',
        'footer_links_title': 'Linkuri Utile',
        'footer_privacy': 'Politica de confidențialitate',
        'footer_terms': 'Termeni și condiții',
        'footer_social_title': 'Social Media',
        'footer_about': 'Expertul tău în soluții premium și inovatoare, din tablă, pentru casă și acoperiș!',
        'footer_rights': 'Toate drepturile rezervate.',
        'article_1_title': 'De ce să folosim jgheaburi si burlane din Aluminiu?',
        'article_1_desc': 'Proprietățile anti-coroziune ale aluminiului si procesul special de vopsire ii conferă o durabilitate mare in timp.',
        'privacy_content': 'Confidențialitatea datelor dumneavoastră este importantă pentru noi. Această politică explică modul în care colectăm, utilizăm și protejăm informațiile dumneavoastră personale.',
        'terms_content': 'Prin accesarea acestui site, sunteți de acord cu acești termeni și condiții. Vă rugăm să îi citiți cu atenție înainte de a utiliza serviciile noastre.',
        'read_more': 'Citește mai mult',
        'project_1_title': 'Jgheaburi Aluminiu',
        'project_1_desc': 'Sistem complet fără îmbinări',
        'project_2_title': 'Acoperiș Rezidențial',
        'project_2_desc': 'Montaj profesional țiglă metalică',
        'project_3_title': 'Complex Comercial',
        'project_3_desc': 'Sistem pluvial industrial',
        'project_4_title': 'Burlane Rectangulare',
        'project_4_desc': 'Design modern și eficient',
        'estimate_title': 'Estimare Cost Sistem Pluvial',
        'roof_type_label': 'Tip Acoperiș',
        'gutters_label': 'Lungime Jgheaburi (metri)',
        'downspouts_label': 'Lungime Burlane (metri)',
        'material_label': 'Material',
        'calculate_btn': 'Calculează Estimare',
        'cost_result_title': 'Cost Estimat:',
        'cost_result_title': 'Cost Estimat:',
        'cost_disclaimer': '*Aceasta este o estimare strict informativă. Prețul final poate varia în funcție de complexitatea montajului și accesorii suplimentare.',
        'roof_2_slopes': '2 Ape (Simplu)',
        'roof_4_slopes': '4 Ape (Complex)',
        'roof_multi': 'Multivolum (Foarte Complex)',
        'mat_zinc': 'Tablă Zincată (Standard)',
        'mat_alum': 'Aluminiu (Premium)',
        'mat_copper': 'Cupru (Exclusiv)',
        'back_home': 'Înapoi acasă',
        'project_details_title': 'Detalii Proiect',
        'project_location_label': 'Locație:',
        'project_year_label': 'An:',
        'project_material_label': 'Material:',
        'project_desc_title': 'Descriere',
        'project_1_location': 'București',
        'project_1_year': '2023',
        'project_1_material': 'Aluminiu',
        'project_1_full_desc': 'Acest proiect a implicat instalarea unui sistem complet de jgheaburi și burlane din aluminiu pentru o vilă modernă. Am folosit tehnologia noastră de jgheaburi fără îmbinări pentru a asigura o durabilitate maximă și un aspect estetic impecabil.',
        'project_2_location': 'Ilfov',
        'project_2_year': '2023',
        'project_2_material': 'Tablă Zincată',
        'project_2_full_desc': 'Pentru acest acoperiș rezidențial complex, am furnizat și montat un sistem pluvial personalizat. Provocarea a fost adaptarea la multiplele pante ale acoperișului, asigurând o scurgere eficientă a apei.',
        'project_3_location': 'Cluj-Napoca',
        'project_3_year': '2022',
        'project_3_material': 'Oțel',
        'project_3_full_desc': 'Un proiect de anvergură pentru un complex comercial. Am instalat un sistem industrial capabil să gestioneze volume mari de apă pluvială, folosind materiale rezistente la coroziune și trafic intens.',
        'project_4_location': 'Brașov',
        'project_4_year': '2024',
        'project_4_material': 'Cupru',
        'project_4_full_desc': 'Renovarea unei case istorice a necesitat o atenție deosebită la detalii. Am ales burlane rectangulare din cupru pentru a se integra perfect în arhitectura clădirii, oferind în același timp o soluție modernă de drenaj.',
        'service_desc_title': 'Despre Serviciu',
        'service_1_full_desc': 'Oferim consultanță specializată în design arhitectural pentru sistemele pluviale. Înțelegem că fiecare clădire este unică, așa că proiectăm soluții care nu doar evacuează apa eficient, ci și completează estetica fațadei. De la alegerea culorilor până la forma jgheaburilor, totul este personalizat.',
        'service_feature_1': 'Consultanță estetică',
        'service_feature_2': 'Personalizare culori',
        'service_feature_3': 'Integrare arhitecturală',
        'service_2_full_desc': 'Calitatea este prioritatea noastră numărul unu. Folosim doar materiale premium, testate pentru a rezista la condiții meteo extreme. Oferim garanții extinse pentru a vă asigura liniștea sufletească pe termen lung.',
        'service_feature_4': 'Garanție 30 ani',
        'service_feature_5': 'Materiale premium',
        'service_feature_6': 'Rezistență la coroziune',
        'service_3_full_desc': 'Echipa noastră este formată din profesioniști cu experiență vastă în domeniu. Dispunem de ateliere mobile complet echipate, ceea ce ne permite să fabricăm jgheaburile direct la locația dumneavoastră, asigurând o potrivire perfectă și reducând pierderile de material.',
        'service_feature_7': 'Montaj rapid',
        'service_feature_8': 'Atelier mobil',
        'service_feature_9': 'Personal calificat'
    },
    'en': {
        'nav_home': 'Home',
        'nav_about': 'About Us',
        'nav_products': 'Products & Services',
        'nav_projects': 'Projects',
        'nav_articles': 'Articles',
        'nav_contact': 'Contact',
        'nav_estimate': 'Cost Estimate',
        'hero_title': 'Premium Rainwater Systems',
        'hero_subtitle': 'Innovative sheet metal solutions for your home and roof. Seamless, worry-free.',
        'hero_cta': 'View Projects',
        'services_title': 'Our Products & Services',
        'service_1_title': 'Architectural Design',
        'service_1_desc': 'Your home architecture needs quality and functional finishes.',
        'service_2_title': 'Guaranteed Quality',
        'service_2_desc': '30 Years Technical Warranty + 20 Years Aesthetic Warranty.',
        'service_3_title': 'Professional Team',
        'service_3_desc': 'On-site manufacturing and professional installation.',
        'stats_projects': 'Projects Completed',
        'stats_gutters': 'Meters of Gutters',
        'stats_clients': 'Happy Clients',
        'projects_title': 'Recent Projects',
        'testimonials_title': 'What Clients Say',
        'contact_title': 'Contact Us',
        'contact_name': 'Name',
        'contact_email': 'Email',
        'contact_message': 'Message',
        'contact_send': 'Send Message',
        'contact_phone_label': 'Phone',
        'contact_email_label': 'Email',
        'contact_schedule_label': 'Schedule',
        'footer_links_title': 'Useful Links',
        'footer_privacy': 'Privacy Policy',
        'footer_terms': 'Terms and Conditions',
        'footer_social_title': 'Social Media',
        'footer_about': 'Your expert in premium and innovative sheet metal solutions for home and roof!',
        'footer_rights': 'All rights reserved.',
        'article_1_title': 'Why use Aluminum gutters and downspouts?',
        'article_1_desc': 'Aluminum\'s anti-corrosion properties and special painting process give it great durability over time.',
        'privacy_content': 'Your data privacy is important to us. This policy explains how we collect, use, and protect your personal information.',
        'terms_content': 'By accessing this site, you agree to these terms and conditions. Please read them carefully before using our services.',
        'read_more': 'Read More',
        'project_1_title': 'Aluminum Gutters',
        'project_1_desc': 'Complete seamless system',
        'project_2_title': 'Residential Roof',
        'project_2_desc': 'Professional metal tile installation',
        'project_3_title': 'Commercial Complex',
        'project_3_desc': 'Industrial rainwater system',
        'project_4_title': 'Rectangular Downspouts',
        'project_4_desc': 'Modern and efficient design',
        'estimate_title': 'Rainwater System Cost Estimate',
        'roof_type_label': 'Roof Type',
        'gutters_label': 'Gutters Length (meters)',
        'downspouts_label': 'Downspouts Length (meters)',
        'material_label': 'Material',
        'calculate_btn': 'Calculate Estimate',
        'cost_result_title': 'Estimated Cost:',
        'cost_result_title': 'Estimated Cost:',
        'cost_disclaimer': '*This is a strictly informative estimate. The final price may vary depending on installation complexity and additional accessories.',
        'roof_2_slopes': '2 Slopes (Simple)',
        'roof_4_slopes': '4 Slopes (Complex)',
        'roof_multi': 'Multi-volume (Very Complex)',
        'mat_zinc': 'Zinc Sheet (Standard)',
        'mat_alum': 'Aluminum (Premium)',
        'mat_copper': 'Copper (Exclusive)',
        'back_home': 'Back Home',
        'project_details_title': 'Project Details',
        'project_location_label': 'Location:',
        'project_year_label': 'Year:',
        'project_material_label': 'Material:',
        'project_desc_title': 'Description',
        'project_1_location': 'Bucharest',
        'project_1_year': '2023',
        'project_1_material': 'Aluminum',
        'project_1_full_desc': 'This project involved the installation of a complete aluminum gutter and downspout system for a modern villa. We used our seamless gutter technology to ensure maximum durability and a flawless aesthetic appearance.',
        'project_2_location': 'Ilfov',
        'project_2_year': '2023',
        'project_2_material': 'Zinc Sheet',
        'project_2_full_desc': 'For this complex residential roof, we supplied and installed a custom rainwater system. The challenge was adapting to the multiple slopes of the roof, ensuring efficient water drainage.',
        'project_3_location': 'Cluj-Napoca',
        'project_3_year': '2022',
        'project_3_material': 'Steel',
        'project_3_full_desc': 'A large-scale project for a commercial complex. We installed an industrial system capable of handling large volumes of rainwater, using materials resistant to corrosion and heavy traffic.',
        'project_4_location': 'Brasov',
        'project_4_year': '2024',
        'project_4_material': 'Copper',
        'project_4_full_desc': 'The renovation of a historical house required special attention to detail. We chose rectangular copper downspouts to integrate perfectly into the building\'s architecture while offering a modern drainage solution.',
        'service_desc_title': 'About Service',
        'service_1_full_desc': 'We offer specialized consulting in architectural design for rainwater systems. We understand that every building is unique, so we design solutions that not only drain water efficiently but also complement the facade aesthetics. From color selection to gutter shape, everything is customized.',
        'service_feature_1': 'Aesthetic consulting',
        'service_feature_2': 'Color customization',
        'service_feature_3': 'Architectural integration',
        'service_2_full_desc': 'Quality is our number one priority. We use only premium materials, tested to withstand extreme weather conditions. We offer extended warranties to ensure your long-term peace of mind.',
        'service_feature_4': '30-year warranty',
        'service_feature_5': 'Premium materials',
        'service_feature_6': 'Corrosion resistance',
        'service_3_full_desc': 'Our team consists of professionals with vast experience in the field. We have fully equipped mobile workshops, allowing us to manufacture gutters directly at your location, ensuring a perfect fit and reducing material waste.',
        'service_feature_7': 'Fast installation',
        'service_feature_8': 'Mobile workshop',
        'service_feature_9': 'Qualified personnel'
    },
    'es': {
        'nav_home': 'Inicio',
        'nav_about': 'Sobre Nosotros',
        'nav_products': 'Productos y Servicios',
        'nav_projects': 'Proyectos',
        'nav_articles': 'Artículos',
        'nav_contact': 'Contacto',
        'nav_estimate': 'Estimación de Costos',
        'hero_title': 'Sistemas Pluviales Premium',
        'hero_subtitle': 'Soluciones innovadoras de chapa para su hogar y techo. Sin juntas, sin preocupaciones.',
        'hero_cta': 'Ver Proyectos',
        'services_title': 'Nuestros Productos y Servicios',
        'service_1_title': 'Diseño Arquitectónico',
        'service_1_desc': 'La arquitectura de su hogar necesita acabados de calidad y funcionales.',
        'service_2_title': 'Calidad Garantizada',
        'service_2_desc': 'Garantía Técnica de 30 años + Garantía Estética de 20 años.',
        'service_3_title': 'Equipo Profesional',
        'service_3_desc': 'Fabricación in situ e instalación profesional.',
        'stats_projects': 'Proyectos Completados',
        'stats_gutters': 'Metros de Canalones',
        'stats_clients': 'Clientes Felices',
        'projects_title': 'Proyectos Recientes',
        'testimonials_title': 'Lo Que Dicen Los Clientes',
        'contact_title': 'Contáctenos',
        'contact_name': 'Nombre',
        'contact_email': 'Correo',
        'contact_message': 'Mensaje',
        'contact_send': 'Enviar Mensaje',
        'contact_phone_label': 'Teléfono',
        'contact_email_label': 'Correo',
        'contact_schedule_label': 'Horario',
        'footer_links_title': 'Enlaces Útiles',
        'footer_privacy': 'Política de Privacidad',
        'footer_terms': 'Términos y Condiciones',
        'footer_social_title': 'Redes Sociales',
        'footer_about': '¡Su experto en soluciones de chapa premium e innovadoras para el hogar y el techo!',
        'footer_rights': 'Todos los derechos reservados.',
        'article_1_title': '¿Por qué usar canalones y bajantes de aluminio?',
        'article_1_desc': 'Las propiedades anticorrosivas del aluminio y el proceso especial de pintura le confieren una gran durabilidad en el tiempo.',
        'privacy_content': 'La privacidad de sus datos es importante para nosotros. Esta política explica cómo recopilamos, usamos y protegemos su información personal.',
        'terms_content': 'Al acceder a este sitio, acepta estos términos y condiciones. Por favor, léalos atentamente antes de utilizar nuestros servicios.',
        'read_more': 'Leer Más',
        'project_1_title': 'Canalones de Aluminio',
        'project_1_desc': 'Sistema completo sin juntas',
        'project_2_title': 'Techo Residencial',
        'project_2_desc': 'Instalación profesional de tejas metálicas',
        'project_3_title': 'Complejo Comercial',
        'project_3_desc': 'Sistema pluvial industrial',
        'project_4_title': 'Bajantes Rectangulares',
        'project_4_desc': 'Diseño moderno y eficiente',
        'estimate_title': 'Estimación de Costo del Sistema Pluvial',
        'roof_type_label': 'Tipo de Techo',
        'gutters_label': 'Longitud de Canalones (metros)',
        'downspouts_label': 'Longitud de Bajantes (metros)',
        'material_label': 'Material',
        'calculate_btn': 'Calcular Estimación',
        'cost_result_title': 'Costo Estimado:',
        'cost_result_title': 'Costo Estimado:',
        'cost_disclaimer': '*Esta es una estimación estrictamente informativa. El precio final puede variar según la complejidad de la instalación y los accesorios adicionales.',
        'roof_2_slopes': '2 Aguas (Simple)',
        'roof_4_slopes': '4 Aguas (Complejo)',
        'roof_multi': 'Multivolumen (Muy Complejo)',
        'mat_zinc': 'Chapa de Zinc (Estándar)',
        'mat_alum': 'Aluminio (Premium)',
        'mat_copper': 'Cobre (Exclusivo)',
        'back_home': 'Volver al Inicio',
        'project_details_title': 'Detalles del Proyecto',
        'project_location_label': 'Ubicación:',
        'project_year_label': 'Año:',
        'project_material_label': 'Material:',
        'project_desc_title': 'Descripción',
        'project_1_location': 'Bucarest',
        'project_1_year': '2023',
        'project_1_material': 'Aluminio',
        'project_1_full_desc': 'Este proyecto implicó la instalación de un sistema completo de canalones y bajantes de aluminio para una villa moderna. Utilizamos nuestra tecnología de canalones sin juntas para garantizar la máxima durabilidad y una apariencia estética impecable.',
        'project_2_location': 'Ilfov',
        'project_2_year': '2023',
        'project_2_material': 'Chapa de Zinc',
        'project_2_full_desc': 'Para este complejo techo residencial, suministramos e instalamos un sistema pluvial personalizado. El desafío fue adaptarse a las múltiples pendientes del techo, asegurando un drenaje eficiente del agua.',
        'project_3_location': 'Cluj-Napoca',
        'project_3_year': '2022',
        'project_3_material': 'Acero',
        'project_3_full_desc': 'Un proyecto a gran escala para un complejo comercial. Instalamos un sistema industrial capaz de manejar grandes volúmenes de agua de lluvia, utilizando materiales resistentes a la corrosión y al tráfico intenso.',
        'project_4_location': 'Brasov',
        'project_4_year': '2024',
        'project_4_material': 'Cobre',
        'project_4_full_desc': 'La renovación de una casa histórica requirió una atención especial a los detalles. Elegimos bajantes rectangulares de cobre para integrarse perfectamente en la arquitectura del edificio, ofreciendo al mismo tiempo una solución moderna de drenaje.',
        'service_desc_title': 'Sobre el Servicio',
        'service_1_full_desc': 'Ofrecemos consultoría especializada en diseño arquitectónico para sistemas pluviales. Entendemos que cada edificio es único, por lo que diseñamos soluciones que no solo drenan el agua de manera eficiente, sino que también complementan la estética de la fachada. Desde la selección del color hasta la forma de los canalones, todo está personalizado.',
        'service_feature_1': 'Consultoría estética',
        'service_feature_2': 'Personalización de color',
        'service_feature_3': 'Integración arquitectónica',
        'service_2_full_desc': 'La calidad es nuestra prioridad número uno. Utilizamos solo materiales premium, probados para resistir condiciones climáticas extremas. Ofrecemos garantías extendidas para asegurar su tranquilidad a largo plazo.',
        'service_feature_4': 'Garantía de 30 años',
        'service_feature_5': 'Materiales premium',
        'service_feature_6': 'Resistencia a la corrosión',
        'service_3_full_desc': 'Nuestro equipo está formado por profesionales con amplia experiencia en el campo. Disponemos de talleres móviles totalmente equipados, lo que nos permite fabricar canalones directamente en su ubicación, asegurando un ajuste perfecto y reduciendo el desperdicio de material.',
        'service_feature_7': 'Instalación rápida',
        'service_feature_8': 'Taller móvil',
        'service_feature_9': 'Personal calificado'
    },
    'it': {
        'nav_home': 'Home',
        'nav_about': 'Chi Siamo',
        'nav_products': 'Prodotti e Servizi',
        'nav_projects': 'Progetti',
        'nav_articles': 'Articoli',
        'nav_contact': 'Contatto',
        'nav_estimate': 'Preventivo',
        'hero_title': 'Sistemi Pluviali Premium',
        'hero_subtitle': 'Soluzioni innovative in lamiera per la tua casa e il tetto. Senza giunture, senza pensieri.',
        'hero_cta': 'Vedi Progetti',
        'services_title': 'I Nostri Prodotti e Servizi',
        'service_1_title': 'Design Architettonico',
        'service_1_desc': 'L\'architettura della tua casa ha bisogno di finiture di qualità e funzionali.',
        'service_2_title': 'Qualità Garantita',
        'service_2_desc': 'Garanzia Tecnica 30 anni + Garanzia Estetica 20 anni.',
        'service_3_title': 'Team Professionale',
        'service_3_desc': 'Produzione in loco e installazione professionale.',
        'stats_projects': 'Progetti Completati',
        'stats_gutters': 'Metri di Grondaie',
        'stats_clients': 'Clienti Soddisfatti',
        'projects_title': 'Progetti Recenti',
        'testimonials_title': 'Cosa Dicono i Clienti',
        'contact_title': 'Contattaci',
        'contact_name': 'Nome',
        'contact_email': 'Email',
        'contact_message': 'Messaggio',
        'contact_send': 'Invia Messaggio',
        'contact_phone_label': 'Telefono',
        'contact_email_label': 'Email',
        'contact_schedule_label': 'Orario',
        'footer_links_title': 'Link Utili',
        'footer_privacy': 'Politica sulla Privacy',
        'footer_terms': 'Termini e Condizioni',
        'footer_social_title': 'Social Media',
        'footer_about': 'Il tuo esperto in soluzioni premium e innovative in lamiera per casa e tetto!',
        'footer_rights': 'Tutti i diritti riservati.',
        'article_1_title': 'Perché usare grondaie e pluviali in alluminio?',
        'article_1_desc': 'Le proprietà anticorrosione dell\'alluminio e lo speciale processo di verniciatura gli conferiscono una grande durata nel tempo.',
        'privacy_content': 'La privacy dei tuoi dati è importante per noi. Questa politica spiega come raccogliamo, utilizziamo e proteggiamo le tue informazioni personali.',
        'terms_content': 'Accedendo a questo sito, accetti questi termini e condizioni. Si prega di leggerli attentamente prima di utilizzare i nostri servizi.',
        'read_more': 'Leggi di più',
        'project_1_title': 'Grondaie in Alluminio',
        'project_1_desc': 'Sistema completo senza giunture',
        'project_2_title': 'Tetto Residenziale',
        'project_2_desc': 'Installazione professionale tegole metalliche',
        'project_3_title': 'Complesso Commerciale',
        'project_3_desc': 'Sistema pluviale industriale',
        'project_4_title': 'Pluviali Rettangolari',
        'project_4_desc': 'Design moderno ed efficiente',
        'estimate_title': 'Preventivo Sistema Pluviale',
        'roof_type_label': 'Tipo di Tetto',
        'gutters_label': 'Lunghezza Grondaie (metri)',
        'downspouts_label': 'Lunghezza Pluviali (metri)',
        'material_label': 'Materiale',
        'calculate_btn': 'Calcola Preventivo',
        'cost_result_title': 'Costo Stimato:',
        'cost_result_title': 'Costo Stimato:',
        'cost_disclaimer': '*Questa è una stima puramente informativa. Il prezzo finale può variare in base alla complessità dell\'installazione e agli accessori aggiuntivi.',
        'roof_2_slopes': '2 Falde (Semplice)',
        'roof_4_slopes': '4 Falde (Complesso)',
        'roof_multi': 'Multivolume (Molto Complesso)',
        'mat_zinc': 'Lamiera Zincata (Standard)',
        'mat_alum': 'Alluminio (Premium)',
        'mat_copper': 'Rame (Esclusivo)',
        'back_home': 'Torna alla Home',
        'project_details_title': 'Dettagli Progetto',
        'project_location_label': 'Posizione:',
        'project_year_label': 'Anno:',
        'project_material_label': 'Materiale:',
        'project_desc_title': 'Descrizione',
        'project_1_location': 'Bucarest',
        'project_1_year': '2023',
        'project_1_material': 'Alluminio',
        'project_1_full_desc': 'Questo progetto ha comportato l\'installazione di un sistema completo di grondaie e pluviali in alluminio per una villa moderna. Abbiamo utilizzato la nostra tecnologia di grondaie senza giunture per garantire la massima durata e un aspetto estetico impeccabile.',
        'project_2_location': 'Ilfov',
        'project_2_year': '2023',
        'project_2_material': 'Lamiera Zincata',
        'project_2_full_desc': 'Per questo complesso tetto residenziale, abbiamo fornito e installato un sistema pluviale personalizzato. La sfida è stata adattarsi alle molteplici pendenze del tetto, garantendo un drenaggio efficiente dell\'acqua.',
        'project_3_location': 'Cluj-Napoca',
        'project_3_year': '2022',
        'project_3_material': 'Acciaio',
        'project_3_full_desc': 'Un progetto su larga scala per un complesso commerciale. Abbiamo installato un sistema industriale in grado di gestire grandi volumi di acqua piovana, utilizzando materiali resistenti alla corrosione e al traffico intenso.',
        'project_4_location': 'Brasov',
        'project_4_year': '2024',
        'project_4_material': 'Rame',
        'project_4_full_desc': 'La ristrutturazione di una casa storica ha richiesto una particolare attenzione ai dettagli. Abbiamo scelto pluviali rettangolari in rame per integrarsi perfettamente nell\'architettura dell\'edificio, offrendo allo stesso tempo una soluzione moderna di drenaggio.',
        'service_desc_title': 'Sul Servizio',
        'service_1_full_desc': 'Offriamo consulenza specializzata in design architettonico per sistemi pluviali. Comprendiamo che ogni edificio è unico, quindi progettiamo soluzioni che non solo drenano l\'acqua in modo efficiente, ma completano anche l\'estetica della facciata. Dalla scelta del colore alla forma delle grondaie, tutto è personalizzato.',
        'service_feature_1': 'Consulenza estetica',
        'service_feature_2': 'Personalizzazione colore',
        'service_feature_3': 'Integrazione architettonica',
        'service_2_full_desc': 'La qualità è la nostra priorità numero uno. Utilizziamo solo materiali premium, testati per resistere a condizioni meteorologiche estreme. Offriamo garanzie estese per garantire la tua tranquillità a lungo termine.',
        'service_feature_4': 'Garanzia 30 anni',
        'service_feature_5': 'Materiali premium',
        'service_feature_6': 'Resistenza alla corrosione',
        'service_3_full_desc': 'Il nostro team è composto da professionisti con vasta esperienza nel settore. Disponiamo di officine mobili completamente attrezzate, che ci consentono di produrre grondaie direttamente presso la tua sede, garantendo una vestibilità perfetta e riducendo gli sprechi di materiale.',
        'service_feature_7': 'Installazione rapida',
        'service_feature_8': 'Officina mobile',
        'service_feature_9': 'Personale qualificato'
    }
};
